// 指定使用 proto3 语法

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mq_payload.proto

// 命名空间

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义真正的消息载荷
type MqPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 使用 fixed64，强制固定占用 8 字节，关闭 Varint 压缩！
	// 效率最高，体积最小！
	MsgId uint64 `protobuf:"fixed64,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Type  int32  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	// 几万、几十万的小数字，就用 int64 (享受 Varint 压缩)
	UserId        int64  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SenderId      int64  `protobuf:"varint,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       []byte `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MqPayload) Reset() {
	*x = MqPayload{}
	mi := &file_mq_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MqPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqPayload) ProtoMessage() {}

func (x *MqPayload) ProtoReflect() protoreflect.Message {
	mi := &file_mq_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqPayload.ProtoReflect.Descriptor instead.
func (*MqPayload) Descriptor() ([]byte, []int) {
	return file_mq_payload_proto_rawDescGZIP(), []int{0}
}

func (x *MqPayload) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MqPayload) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MqPayload) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MqPayload) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MqPayload) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_mq_payload_proto protoreflect.FileDescriptor

const file_mq_payload_proto_rawDesc = "" +
	"\n" +
	"\x10mq_payload.proto\x12(instant_messaging_with_websocket_gateway\"\x86\x01\n" +
	"\tMqPayload\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x06R\x05msgId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontentB)\n" +
	"\x1csrc.main.java.com.dely.im.pbP\x01Z\a./pb;pbb\x06proto3"

var (
	file_mq_payload_proto_rawDescOnce sync.Once
	file_mq_payload_proto_rawDescData []byte
)

func file_mq_payload_proto_rawDescGZIP() []byte {
	file_mq_payload_proto_rawDescOnce.Do(func() {
		file_mq_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mq_payload_proto_rawDesc), len(file_mq_payload_proto_rawDesc)))
	})
	return file_mq_payload_proto_rawDescData
}

var file_mq_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mq_payload_proto_goTypes = []any{
	(*MqPayload)(nil), // 0: instant_messaging_with_websocket_gateway.MqPayload
}
var file_mq_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mq_payload_proto_init() }
func file_mq_payload_proto_init() {
	if File_mq_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mq_payload_proto_rawDesc), len(file_mq_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mq_payload_proto_goTypes,
		DependencyIndexes: file_mq_payload_proto_depIdxs,
		MessageInfos:      file_mq_payload_proto_msgTypes,
	}.Build()
	File_mq_payload_proto = out.File
	file_mq_payload_proto_goTypes = nil
	file_mq_payload_proto_depIdxs = nil
}
