server:
  port: 8001

spring:
  application:
    name: store-consumer
  profiles:
    include: secret  # 引入密码配置文件（application-secret.yml）
  datasource:
    url: jdbc:postgresql://192.168.100.131:5432/instant_messaging
    username: postgres
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 3
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 200  # 连接池最大活跃连接数
          max-idle: 50     # 最大空闲连接数
          min-idle: 10     # 最小空闲连接数（保证随时有可用连接，防冷启动抖动）
          max-wait: 1000ms # 当池满时，获取连接的最大等待时间，超时抛异常，触发降级
  rabbitmq:
    addresses: 192.168.100.131
    port: 5672
    username: dogeggly
    listener:
      simple:
        prefetch: 1 # 每次从队列中获取消息的数量，即客户端必须处理完消息并返回确认信息后mq才会再次投递
        acknowledge-mode: manual # 保持手动 ACK
        retry:
          enabled: true # 开启消费者重试
          initial-interval: 1000ms # 第一次重试间隔 1 秒
          multiplier: 2.0 # 每次重试间隔翻倍（指数退避策略）
          max-interval: 10000ms # 最大间隔 10 秒
          max-attempts: 3 # 总共尝试 3 次（包含第一次正常消费）

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dely.im.entity # 别名扫描包
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.dely.chat:
      mapper: debug
      service: info
      controller: info