// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mq_payload.proto
// Protobuf Java Version: 4.34.1

package com.dely.im.pb;

/**
 * <pre>
 * 定义全局唯一的事件枚举字典
 * </pre>
 *
 * Protobuf enum {@code instant_messaging_with_websocket_gateway.EventType}
 */
@com.google.protobuf.Generated
public enum EventType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Protobuf 的硬性规定：枚举的第一个值必须是 0！
   * 我们可以把它作为默认值或未知类型，防止兼容性问题
   * </pre>
   *
   * <code>UNKNOWN_EVENT = 0;</code>
   */
  UNKNOWN_EVENT(0),
  /**
   * <pre>
   * 核心聊天事件
   * </pre>
   *
   * <code>CHAT_MSG = 1;</code>
   */
  CHAT_MSG(1),
  /**
   * <pre>
   * 系统控制事件
   * </pre>
   *
   * <code>SYS_KICK_OUT = 5;</code>
   */
  SYS_KICK_OUT(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "EventType");
  }
  /**
   * <pre>
   * Protobuf 的硬性规定：枚举的第一个值必须是 0！
   * 我们可以把它作为默认值或未知类型，防止兼容性问题
   * </pre>
   *
   * <code>UNKNOWN_EVENT = 0;</code>
   */
  public static final int UNKNOWN_EVENT_VALUE = 0;
  /**
   * <pre>
   * 核心聊天事件
   * </pre>
   *
   * <code>CHAT_MSG = 1;</code>
   */
  public static final int CHAT_MSG_VALUE = 1;
  /**
   * <pre>
   * 系统控制事件
   * </pre>
   *
   * <code>SYS_KICK_OUT = 5;</code>
   */
  public static final int SYS_KICK_OUT_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EventType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EventType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_EVENT;
      case 1: return CHAT_MSG;
      case 5: return SYS_KICK_OUT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EventType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EventType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
          public EventType findValueByNumber(int number) {
            return EventType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.dely.im.pb.MqPayloadOuterClass.getDescriptor().getEnumType(0);
  }

  private static final EventType[] VALUES = values();

  public static EventType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EventType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:instant_messaging_with_websocket_gateway.EventType)
}

