// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mq_payload.proto
// Protobuf Java Version: 4.34.1

package src.main.java.com.dely.im.pb;

@com.google.protobuf.Generated
public final class MqPayloadOuterClass extends com.google.protobuf.GeneratedFile {
  private MqPayloadOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "MqPayloadOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instant_messaging_with_websocket_gateway_MqPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_instant_messaging_with_websocket_gateway_MqPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020mq_payload.proto\022(instant_messaging_wi" +
      "th_websocket_gateway\"^\n\tMqPayload\022\016\n\006msg" +
      "_id\030\001 \001(\006\022\014\n\004type\030\002 \001(\005\022\017\n\007user_id\030\003 \001(\003" +
      "\022\021\n\tsender_id\030\004 \001(\003\022\017\n\007content\030\005 \001(\014B)\n\034" +
      "src.main.java.com.dely.im.pbP\001Z\007./pb;pbb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_instant_messaging_with_websocket_gateway_MqPayload_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_instant_messaging_with_websocket_gateway_MqPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_instant_messaging_with_websocket_gateway_MqPayload_descriptor,
        new java.lang.String[] { "MsgId", "Type", "UserId", "SenderId", "Content", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
