// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mq_payload.proto
// Protobuf Java Version: 4.34.1

package com.dely.im.pb;

/**
 * <pre>
 * 定义真正的消息载荷
 * </pre>
 *
 * Protobuf type {@code instant_messaging_with_websocket_gateway.MqPayload}
 */
@com.google.protobuf.Generated
public final class MqPayload extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:instant_messaging_with_websocket_gateway.MqPayload)
    MqPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "MqPayload");
  }
  // Use MqPayload.newBuilder() to construct.
  private MqPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MqPayload() {
    content_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dely.im.pb.MqPayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqPayload_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.dely.im.pb.MqPayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqPayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dely.im.pb.MqPayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dely.im.pb.MqPayload.class, com.dely.im.pb.MqPayload.Builder.class);
  }

  public static final int MSG_ID_FIELD_NUMBER = 1;
  private long msgId_ = 0L;
  /**
   * <pre>
   * 使用 fixed64，强制固定占用 8 字节，关闭 Varint 压缩！
   * 效率最高，体积最小！
   * </pre>
   *
   * <code>fixed64 msg_id = 1;</code>
   * @return The msgId.
   */
  @java.lang.Override
  public long getMsgId() {
    return msgId_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_ = 0;
  /**
   * <code>int32 type = 2;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int USER_ID_FIELD_NUMBER = 3;
  private long userId_ = 0L;
  /**
   * <pre>
   * 几万、几十万的小数字，就用 int64 (享受 Varint 压缩)
   * </pre>
   *
   * <code>int64 user_id = 3;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int SENDER_ID_FIELD_NUMBER = 4;
  private long senderId_ = 0L;
  /**
   * <code>int64 sender_id = 4;</code>
   * @return The senderId.
   */
  @java.lang.Override
  public long getSenderId() {
    return senderId_;
  }

  public static final int CONTENT_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes content = 5;</code>
   * @return The content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getContent() {
    return content_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgId_ != 0L) {
      output.writeFixed64(1, msgId_);
    }
    if (type_ != 0) {
      output.writeInt32(2, type_);
    }
    if (userId_ != 0L) {
      output.writeInt64(3, userId_);
    }
    if (senderId_ != 0L) {
      output.writeInt64(4, senderId_);
    }
    if (!content_.isEmpty()) {
      output.writeBytes(5, content_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(1, msgId_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, type_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, userId_);
    }
    if (senderId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, senderId_);
    }
    if (!content_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, content_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dely.im.pb.MqPayload)) {
      return super.equals(obj);
    }
    com.dely.im.pb.MqPayload other = (com.dely.im.pb.MqPayload) obj;

    if (getMsgId()
        != other.getMsgId()) return false;
    if (getType()
        != other.getType()) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (getSenderId()
        != other.getSenderId()) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMsgId());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSenderId());
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dely.im.pb.MqPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dely.im.pb.MqPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dely.im.pb.MqPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dely.im.pb.MqPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dely.im.pb.MqPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dely.im.pb.MqPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dely.im.pb.MqPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.dely.im.pb.MqPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dely.im.pb.MqPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dely.im.pb.MqPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dely.im.pb.MqPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.dely.im.pb.MqPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dely.im.pb.MqPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 定义真正的消息载荷
   * </pre>
   *
   * Protobuf type {@code instant_messaging_with_websocket_gateway.MqPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:instant_messaging_with_websocket_gateway.MqPayload)
      com.dely.im.pb.MqPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dely.im.pb.MqPayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dely.im.pb.MqPayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dely.im.pb.MqPayload.class, com.dely.im.pb.MqPayload.Builder.class);
    }

    // Construct using com.dely.im.pb.MqPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      msgId_ = 0L;
      type_ = 0;
      userId_ = 0L;
      senderId_ = 0L;
      content_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dely.im.pb.MqPayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqPayload_descriptor;
    }

    @java.lang.Override
    public com.dely.im.pb.MqPayload getDefaultInstanceForType() {
      return com.dely.im.pb.MqPayload.getDefaultInstance();
    }

    @java.lang.Override
    public com.dely.im.pb.MqPayload build() {
      com.dely.im.pb.MqPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dely.im.pb.MqPayload buildPartial() {
      com.dely.im.pb.MqPayload result = new com.dely.im.pb.MqPayload(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dely.im.pb.MqPayload result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.msgId_ = msgId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.senderId_ = senderId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.content_ = content_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dely.im.pb.MqPayload) {
        return mergeFrom((com.dely.im.pb.MqPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dely.im.pb.MqPayload other) {
      if (other == com.dely.im.pb.MqPayload.getDefaultInstance()) return this;
      if (other.getMsgId() != 0L) {
        setMsgId(other.getMsgId());
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getSenderId() != 0L) {
        setSenderId(other.getSenderId());
      }
      if (!other.getContent().isEmpty()) {
        setContent(other.getContent());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              msgId_ = input.readFixed64();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 16: {
              type_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              senderId_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              content_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long msgId_ ;
    /**
     * <pre>
     * 使用 fixed64，强制固定占用 8 字节，关闭 Varint 压缩！
     * 效率最高，体积最小！
     * </pre>
     *
     * <code>fixed64 msg_id = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }
    /**
     * <pre>
     * 使用 fixed64，强制固定占用 8 字节，关闭 Varint 压缩！
     * 效率最高，体积最小！
     * </pre>
     *
     * <code>fixed64 msg_id = 1;</code>
     * @param value The msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgId(long value) {

      msgId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用 fixed64，强制固定占用 8 字节，关闭 Varint 压缩！
     * 效率最高，体积最小！
     * </pre>
     *
     * <code>fixed64 msg_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      msgId_ = 0L;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <code>int32 type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>int32 type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {

      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <pre>
     * 几万、几十万的小数字，就用 int64 (享受 Varint 压缩)
     * </pre>
     *
     * <code>int64 user_id = 3;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     * 几万、几十万的小数字，就用 int64 (享受 Varint 压缩)
     * </pre>
     *
     * <code>int64 user_id = 3;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 几万、几十万的小数字，就用 int64 (享受 Varint 压缩)
     * </pre>
     *
     * <code>int64 user_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private long senderId_ ;
    /**
     * <code>int64 sender_id = 4;</code>
     * @return The senderId.
     */
    @java.lang.Override
    public long getSenderId() {
      return senderId_;
    }
    /**
     * <code>int64 sender_id = 4;</code>
     * @param value The senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderId(long value) {

      senderId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sender_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      senderId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes content = 5;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    /**
     * <code>bytes content = 5;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bytes content = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      bitField0_ = (bitField0_ & ~0x00000010);
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:instant_messaging_with_websocket_gateway.MqPayload)
  }

  // @@protoc_insertion_point(class_scope:instant_messaging_with_websocket_gateway.MqPayload)
  private static final com.dely.im.pb.MqPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dely.im.pb.MqPayload();
  }

  public static com.dely.im.pb.MqPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MqPayload>
      PARSER = new com.google.protobuf.AbstractParser<MqPayload>() {
    @java.lang.Override
    public MqPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MqPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MqPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dely.im.pb.MqPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

