// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mq_payload.proto
// Protobuf Java Version: 4.34.1

package com.dely.im.pb;

@com.google.protobuf.Generated
public interface MqPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instant_messaging_with_websocket_gateway.MqPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 使用 fixed64，强制固定占用 8 字节，关闭 Varint 压缩！
   * 效率最高，体积最小！
   * </pre>
   *
   * <code>fixed64 msg_id = 1;</code>
   * @return The msgId.
   */
  long getMsgId();

  /**
   * <code>.instant_messaging_with_websocket_gateway.EventType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.instant_messaging_with_websocket_gateway.EventType type = 2;</code>
   * @return The type.
   */
  com.dely.im.pb.EventType getType();

  /**
   * <pre>
   * 几万、几十万的小数字，就用 int64 (享受 Varint 压缩)
   * </pre>
   *
   * <code>int64 user_id = 3;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 sender_id = 4;</code>
   * @return The senderId.
   */
  long getSenderId();

  /**
   * <code>bytes content = 5;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
