// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mq_payload.proto
// Protobuf Java Version: 4.34.1

package com.dely.im.pb;

@com.google.protobuf.Generated
public final class MqPayloadOuterClass extends com.google.protobuf.GeneratedFile {
  private MqPayloadOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "MqPayloadOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instant_messaging_with_websocket_gateway_MqPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_instant_messaging_with_websocket_gateway_MqPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020mq_payload.proto\022(instant_messaging_wi" +
      "th_websocket_gateway\"\272\001\n\tMqPayload\022\016\n\006ms" +
      "g_id\030\001 \001(\006\022A\n\004type\030\002 \001(\01623.instant_messa" +
      "ging_with_websocket_gateway.EventType\022\020\n" +
      "\010user_ids\030\003 \003(\003\022\021\n\tsender_id\030\004 \001(\003\022\020\n\010gr" +
      "oup_id\030\005 \001(\003\022\017\n\007content\030\006 \001(\014\022\022\n\nextra_d" +
      "ata\030\007 \001(\014*>\n\tEventType\022\021\n\rUNKNOWN_EVENT\020" +
      "\000\022\014\n\010CHAT_MSG\020\001\022\020\n\014SYS_KICK_OUT\020\005B\033\n\016com" +
      ".dely.im.pbP\001Z\007./pb;pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_instant_messaging_with_websocket_gateway_MqPayload_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_instant_messaging_with_websocket_gateway_MqPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_instant_messaging_with_websocket_gateway_MqPayload_descriptor,
        new java.lang.String[] { "MsgId", "Type", "UserIds", "SenderId", "GroupId", "Content", "ExtraData", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
