// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mq_store_payload.proto
// Protobuf Java Version: 4.34.1

package com.dely.im.pb;

@com.google.protobuf.Generated
public final class MqStorePayloadOuterClass extends com.google.protobuf.GeneratedFile {
  private MqStorePayloadOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "MqStorePayloadOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instant_messaging_with_websocket_gateway_MqStorePayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_instant_messaging_with_websocket_gateway_MqStorePayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026mq_store_payload.proto\022(instant_messag" +
      "ing_with_websocket_gateway\"Z\n\016MqStorePay" +
      "load\022\016\n\006msg_id\030\001 \001(\006\022\021\n\tsender_id\030\002 \001(\003\022" +
      "\023\n\013receiver_id\030\003 \001(\003\022\020\n\010is_group\030\004 \001(\010B\022" +
      "\n\016com.dely.im.pbP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_instant_messaging_with_websocket_gateway_MqStorePayload_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_instant_messaging_with_websocket_gateway_MqStorePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_instant_messaging_with_websocket_gateway_MqStorePayload_descriptor,
        new java.lang.String[] { "MsgId", "SenderId", "ReceiverId", "IsGroup", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
