// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mq_store_payload.proto
// Protobuf Java Version: 4.34.1

package com.dely.im.pb;

/**
 * <pre>
 * 定义真正的消息载荷
 * </pre>
 *
 * Protobuf type {@code instant_messaging_with_websocket_gateway.MqStorePayload}
 */
@com.google.protobuf.Generated
public final class MqStorePayload extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:instant_messaging_with_websocket_gateway.MqStorePayload)
    MqStorePayloadOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "MqStorePayload");
  }
  // Use MqStorePayload.newBuilder() to construct.
  private MqStorePayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MqStorePayload() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dely.im.pb.MqStorePayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqStorePayload_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.dely.im.pb.MqStorePayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqStorePayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dely.im.pb.MqStorePayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqStorePayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dely.im.pb.MqStorePayload.class, com.dely.im.pb.MqStorePayload.Builder.class);
  }

  public static final int MSG_ID_FIELD_NUMBER = 1;
  private long msgId_ = 0L;
  /**
   * <code>fixed64 msg_id = 1;</code>
   * @return The msgId.
   */
  @java.lang.Override
  public long getMsgId() {
    return msgId_;
  }

  public static final int SENDER_ID_FIELD_NUMBER = 2;
  private long senderId_ = 0L;
  /**
   * <code>int64 sender_id = 2;</code>
   * @return The senderId.
   */
  @java.lang.Override
  public long getSenderId() {
    return senderId_;
  }

  public static final int RECEIVER_ID_FIELD_NUMBER = 3;
  private long receiverId_ = 0L;
  /**
   * <code>int64 receiver_id = 3;</code>
   * @return The receiverId.
   */
  @java.lang.Override
  public long getReceiverId() {
    return receiverId_;
  }

  public static final int IS_GROUP_FIELD_NUMBER = 4;
  private boolean isGroup_ = false;
  /**
   * <code>bool is_group = 4;</code>
   * @return The isGroup.
   */
  @java.lang.Override
  public boolean getIsGroup() {
    return isGroup_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgId_ != 0L) {
      output.writeFixed64(1, msgId_);
    }
    if (senderId_ != 0L) {
      output.writeInt64(2, senderId_);
    }
    if (receiverId_ != 0L) {
      output.writeInt64(3, receiverId_);
    }
    if (isGroup_ != false) {
      output.writeBool(4, isGroup_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(1, msgId_);
    }
    if (senderId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, senderId_);
    }
    if (receiverId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, receiverId_);
    }
    if (isGroup_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isGroup_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dely.im.pb.MqStorePayload)) {
      return super.equals(obj);
    }
    com.dely.im.pb.MqStorePayload other = (com.dely.im.pb.MqStorePayload) obj;

    if (getMsgId()
        != other.getMsgId()) return false;
    if (getSenderId()
        != other.getSenderId()) return false;
    if (getReceiverId()
        != other.getReceiverId()) return false;
    if (getIsGroup()
        != other.getIsGroup()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMsgId());
    hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSenderId());
    hash = (37 * hash) + RECEIVER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReceiverId());
    hash = (37 * hash) + IS_GROUP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsGroup());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dely.im.pb.MqStorePayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dely.im.pb.MqStorePayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dely.im.pb.MqStorePayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dely.im.pb.MqStorePayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dely.im.pb.MqStorePayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dely.im.pb.MqStorePayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dely.im.pb.MqStorePayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.dely.im.pb.MqStorePayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.dely.im.pb.MqStorePayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.dely.im.pb.MqStorePayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dely.im.pb.MqStorePayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.dely.im.pb.MqStorePayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dely.im.pb.MqStorePayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 定义真正的消息载荷
   * </pre>
   *
   * Protobuf type {@code instant_messaging_with_websocket_gateway.MqStorePayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:instant_messaging_with_websocket_gateway.MqStorePayload)
      com.dely.im.pb.MqStorePayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dely.im.pb.MqStorePayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqStorePayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dely.im.pb.MqStorePayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqStorePayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dely.im.pb.MqStorePayload.class, com.dely.im.pb.MqStorePayload.Builder.class);
    }

    // Construct using com.dely.im.pb.MqStorePayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      msgId_ = 0L;
      senderId_ = 0L;
      receiverId_ = 0L;
      isGroup_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dely.im.pb.MqStorePayloadOuterClass.internal_static_instant_messaging_with_websocket_gateway_MqStorePayload_descriptor;
    }

    @java.lang.Override
    public com.dely.im.pb.MqStorePayload getDefaultInstanceForType() {
      return com.dely.im.pb.MqStorePayload.getDefaultInstance();
    }

    @java.lang.Override
    public com.dely.im.pb.MqStorePayload build() {
      com.dely.im.pb.MqStorePayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dely.im.pb.MqStorePayload buildPartial() {
      com.dely.im.pb.MqStorePayload result = new com.dely.im.pb.MqStorePayload(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.dely.im.pb.MqStorePayload result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.msgId_ = msgId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.senderId_ = senderId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.receiverId_ = receiverId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isGroup_ = isGroup_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dely.im.pb.MqStorePayload) {
        return mergeFrom((com.dely.im.pb.MqStorePayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dely.im.pb.MqStorePayload other) {
      if (other == com.dely.im.pb.MqStorePayload.getDefaultInstance()) return this;
      if (other.getMsgId() != 0L) {
        setMsgId(other.getMsgId());
      }
      if (other.getSenderId() != 0L) {
        setSenderId(other.getSenderId());
      }
      if (other.getReceiverId() != 0L) {
        setReceiverId(other.getReceiverId());
      }
      if (other.getIsGroup() != false) {
        setIsGroup(other.getIsGroup());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              msgId_ = input.readFixed64();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 16: {
              senderId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              receiverId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              isGroup_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long msgId_ ;
    /**
     * <code>fixed64 msg_id = 1;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }
    /**
     * <code>fixed64 msg_id = 1;</code>
     * @param value The msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgId(long value) {

      msgId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>fixed64 msg_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      msgId_ = 0L;
      onChanged();
      return this;
    }

    private long senderId_ ;
    /**
     * <code>int64 sender_id = 2;</code>
     * @return The senderId.
     */
    @java.lang.Override
    public long getSenderId() {
      return senderId_;
    }
    /**
     * <code>int64 sender_id = 2;</code>
     * @param value The senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderId(long value) {

      senderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sender_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      senderId_ = 0L;
      onChanged();
      return this;
    }

    private long receiverId_ ;
    /**
     * <code>int64 receiver_id = 3;</code>
     * @return The receiverId.
     */
    @java.lang.Override
    public long getReceiverId() {
      return receiverId_;
    }
    /**
     * <code>int64 receiver_id = 3;</code>
     * @param value The receiverId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverId(long value) {

      receiverId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 receiver_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiverId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      receiverId_ = 0L;
      onChanged();
      return this;
    }

    private boolean isGroup_ ;
    /**
     * <code>bool is_group = 4;</code>
     * @return The isGroup.
     */
    @java.lang.Override
    public boolean getIsGroup() {
      return isGroup_;
    }
    /**
     * <code>bool is_group = 4;</code>
     * @param value The isGroup to set.
     * @return This builder for chaining.
     */
    public Builder setIsGroup(boolean value) {

      isGroup_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_group = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsGroup() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isGroup_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:instant_messaging_with_websocket_gateway.MqStorePayload)
  }

  // @@protoc_insertion_point(class_scope:instant_messaging_with_websocket_gateway.MqStorePayload)
  private static final com.dely.im.pb.MqStorePayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dely.im.pb.MqStorePayload();
  }

  public static com.dely.im.pb.MqStorePayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MqStorePayload>
      PARSER = new com.google.protobuf.AbstractParser<MqStorePayload>() {
    @java.lang.Override
    public MqStorePayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MqStorePayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MqStorePayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dely.im.pb.MqStorePayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

