// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mq_store_payload.proto
// Protobuf Java Version: 4.34.1

package com.dely.im.pb;

@com.google.protobuf.Generated
public interface MqStorePayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instant_messaging_with_websocket_gateway.MqStorePayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>fixed64 msg_id = 1;</code>
   * @return The msgId.
   */
  long getMsgId();

  /**
   * <code>int64 sender_id = 2;</code>
   * @return The senderId.
   */
  long getSenderId();

  /**
   * <code>int64 receiver_id = 3;</code>
   * @return The receiverId.
   */
  long getReceiverId();

  /**
   * <code>bool is_group = 4;</code>
   * @return The isGroup.
   */
  boolean getIsGroup();
}
